<!-- NAV BAR -->
<nav class = "d-flex navbar navbar-expand-sm bg-light navbar-light sticky-top">
	<ul class="navbar-nav">
		<li class = "nav-item dropdown active">
			<a class="nav-link dropdown-toggle mr-auto" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Projects</a>
			<div class="dropdown-menu">
				<a class="dropdown-item text-decoration-none" href="project1_tributepage.html">Tribute Page</a>
				<a class="dropdown-item text-decoration-none" href="project2_surveyform.html">Survey Form</a>
				<a class="dropdown-item text-decoration-none" href="GuessTheColourGame.html">Guess The Colour Game</a>
				<a class="dropdown-item text-decoration-none" href="Javascript-Drumkit.html">Javascript Drumkit</a>
				<a class="dropdown-item text-decoration-none" href="#javascript-clock">Javascript Clock</a>
				<a class="dropdown-item text-decoration-none" href="JavascriptCalculator.html">Javascript Calculator</a>
			</div>
		</li>
	</ul>
</nav>